/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpendingRouteImport } from './routes/spending'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as NetWorthRouteImport } from './routes/net-worth'
import { Route as InvestmentsRouteImport } from './routes/investments'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiQuotesRouteImport } from './routes/api/quotes'
import { Route as ApiQuoteRouteImport } from './routes/api/quote'
import { Route as ApiPricesRouteImport } from './routes/api/prices'
import { Route as ApiParseRouteImport } from './routes/api/parse'

const SpendingRoute = SpendingRouteImport.update({
  id: '/spending',
  path: '/spending',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const NetWorthRoute = NetWorthRouteImport.update({
  id: '/net-worth',
  path: '/net-worth',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentsRoute = InvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuotesRoute = ApiQuotesRouteImport.update({
  id: '/api/quotes',
  path: '/api/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuoteRoute = ApiQuoteRouteImport.update({
  id: '/api/quote',
  path: '/api/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPricesRoute = ApiPricesRouteImport.update({
  id: '/api/prices',
  path: '/api/prices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiParseRoute = ApiParseRouteImport.update({
  id: '/api/parse',
  path: '/api/parse',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/insights': typeof InsightsRoute
  '/investments': typeof InvestmentsRoute
  '/net-worth': typeof NetWorthRoute
  '/portfolio': typeof PortfolioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/spending': typeof SpendingRoute
  '/api/parse': typeof ApiParseRoute
  '/api/prices': typeof ApiPricesRoute
  '/api/quote': typeof ApiQuoteRoute
  '/api/quotes': typeof ApiQuotesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/insights': typeof InsightsRoute
  '/investments': typeof InvestmentsRoute
  '/net-worth': typeof NetWorthRoute
  '/portfolio': typeof PortfolioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/spending': typeof SpendingRoute
  '/api/parse': typeof ApiParseRoute
  '/api/prices': typeof ApiPricesRoute
  '/api/quote': typeof ApiQuoteRoute
  '/api/quotes': typeof ApiQuotesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/insights': typeof InsightsRoute
  '/investments': typeof InvestmentsRoute
  '/net-worth': typeof NetWorthRoute
  '/portfolio': typeof PortfolioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/spending': typeof SpendingRoute
  '/api/parse': typeof ApiParseRoute
  '/api/prices': typeof ApiPricesRoute
  '/api/quote': typeof ApiQuoteRoute
  '/api/quotes': typeof ApiQuotesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/insights'
    | '/investments'
    | '/net-worth'
    | '/portfolio'
    | '/sitemap.xml'
    | '/spending'
    | '/api/parse'
    | '/api/prices'
    | '/api/quote'
    | '/api/quotes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/insights'
    | '/investments'
    | '/net-worth'
    | '/portfolio'
    | '/sitemap.xml'
    | '/spending'
    | '/api/parse'
    | '/api/prices'
    | '/api/quote'
    | '/api/quotes'
  id:
    | '__root__'
    | '/'
    | '/insights'
    | '/investments'
    | '/net-worth'
    | '/portfolio'
    | '/sitemap.xml'
    | '/spending'
    | '/api/parse'
    | '/api/prices'
    | '/api/quote'
    | '/api/quotes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InsightsRoute: typeof InsightsRoute
  InvestmentsRoute: typeof InvestmentsRoute
  NetWorthRoute: typeof NetWorthRoute
  PortfolioRoute: typeof PortfolioRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SpendingRoute: typeof SpendingRoute
  ApiParseRoute: typeof ApiParseRoute
  ApiPricesRoute: typeof ApiPricesRoute
  ApiQuoteRoute: typeof ApiQuoteRoute
  ApiQuotesRoute: typeof ApiQuotesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spending': {
      id: '/spending'
      path: '/spending'
      fullPath: '/spending'
      preLoaderRoute: typeof SpendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/net-worth': {
      id: '/net-worth'
      path: '/net-worth'
      fullPath: '/net-worth'
      preLoaderRoute: typeof NetWorthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investments': {
      id: '/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof InvestmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quotes': {
      id: '/api/quotes'
      path: '/api/quotes'
      fullPath: '/api/quotes'
      preLoaderRoute: typeof ApiQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quote': {
      id: '/api/quote'
      path: '/api/quote'
      fullPath: '/api/quote'
      preLoaderRoute: typeof ApiQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prices': {
      id: '/api/prices'
      path: '/api/prices'
      fullPath: '/api/prices'
      preLoaderRoute: typeof ApiPricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/parse': {
      id: '/api/parse'
      path: '/api/parse'
      fullPath: '/api/parse'
      preLoaderRoute: typeof ApiParseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InsightsRoute: InsightsRoute,
  InvestmentsRoute: InvestmentsRoute,
  NetWorthRoute: NetWorthRoute,
  PortfolioRoute: PortfolioRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SpendingRoute: SpendingRoute,
  ApiParseRoute: ApiParseRoute,
  ApiPricesRoute: ApiPricesRoute,
  ApiQuoteRoute: ApiQuoteRoute,
  ApiQuotesRoute: ApiQuotesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
